#!/bin/bash
# Run Ecologia during development

rm -r releases/ecologia-2.0
./release.py --no-javadoc --no-sign
cd releases/ecologia-2.0
java -jar ecologia-2.0.jar --logging --verbose --debug --config ../../ecologia.config
